#!/bin/bash
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/"
apt-get update
apt-get install -y r-base r-base-dev libzmq3-dev
