#!/bin/bash
apt-get update
apt-get install -y --no-install-recommends gnupg
echo "deb http://cran.r-project.org/bin/linux/ubuntu jammy-cran40/" >> /etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
apt-get update
apt-get install -y --no-install-recommends libzmq3-dev r-base r-base-dev
