#!/bin/bash
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y "deb http://cran.r-project.org/bin/linux/ubuntu jammy-cran40/"
sudo apt-get update
sudo apt-get install -y r-base r-base-dev libzmq3-dev
